require("user.plugins")
require("user.settings")
require("user.language-servers")

-- Setups
require("user.treesitter")
require("user.telescope")
require("user.nvim-cmp")
require("user.lua-snip")
require("user.null-ls")
require("user.gitsigns")
require("user.nvim-tree")
require("user.lualine")
require("user.todo-comments")
require("user.db")
require("user.daps")
require("user.dap-ui")
require("user.harpoon")
require("user.custom-commands")
require("user.keymappings")
